from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

TASK_STATES = ("backlog", "ready", "active", "review", "done", "blocked")


def read_text(path: Path) -> str:
    if not path.exists():
        return f"Missing: {path.name}"
    return path.read_text(encoding="utf-8-sig").strip()


def task_counts(task_root: Path) -> dict[str, int]:
    return {
        state: len(list((task_root / state).glob("*.md"))) if (task_root / state).exists() else 0
        for state in TASK_STATES
    }


def latest_handoff(handoff_root: Path) -> Path | None:
    handoffs = sorted(handoff_root.glob("*.md")) if handoff_root.exists() else []
    return handoffs[-1] if handoffs else None


def git_summary(repo_root: Path) -> str:
    completed = subprocess.run(
        ["git", "status", "--short", "--branch"],
        cwd=repo_root,
        text=True,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    output = completed.stdout.strip() or completed.stderr.strip()
    return output or "Clean working tree."


def build_snapshot(repo_root: Path) -> str:
    repo_root = Path(repo_root).resolve()
    agent_root = repo_root / ".agent"
    counts = task_counts(agent_root / "tasks")
    handoff = latest_handoff(agent_root / "handoffs")
    count_lines = "\n".join(f"- {state}: {counts[state]}" for state in TASK_STATES)
    handoff_name = handoff.name if handoff else "None"
    return f"""# Generated Project Snapshot

Generated from repository state. Do not edit this file manually.

## Current State
{read_text(agent_root / 'STATE.md')}

## Task Counts
{count_lines}

## Latest Handoff
{handoff_name}

## Git Status
```text
{git_summary(repo_root)}
```

## Recovery Reading Order
1. `.agent/STATE.md`
2. `.agent/ROADMAP.md`
3. `.agent/ARCHITECTURE.md`
4. `.agent/DOMAIN_RULES.md`
5. Active and review task packets
6. `{handoff_name}`
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a concise Agent project snapshot.")
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    output = args.output or repo_root / ".agent" / "generated" / "project-snapshot.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_snapshot(repo_root), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
